import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  userGuideSidebar: [{type: 'autogenerated', dirName: 'user-guide'}],
  developerGuideSidebar: [{type: 'autogenerated', dirName: 'developer-guide'}],
  apiReferenceSidebar: [{type: 'autogenerated', dirName: 'api-reference'}],
};

export default sidebars;
